# <center> PySensCraft - Illustrative examples

**Note**: *this notebook was created for the purpose of providing an instruction of decision problem sensitivity analysis. For in-depth presentation of graphs submodel see* `graphs_examples.ipynb`

In [2]:
from pysenscraft import alternative, criteria, compromise, graphs, probabilistic, ranking
from pysenscraft.compromise import ICRA
import numpy as np

In [3]:
from sympy import Matrix
from IPython.display import display, HTML, Markdown

def pretty_print_alternative(alternative_results):
    print(f'Alternative index: {alternative_results[0]}')
    print(f'Criteria index: {alternative_results[1]}')
    print(f'Change: {alternative_results[2]}')
    print(f'Resulting decision matrix:') 
    display(Matrix(alternative_results[3]))

def pretty_print_alternative_removal(alternative_results):
    print(f'Alternative index: {alternative_results[0]}')
    print(f'Resulting decision matrix:') 
    display(Matrix(alternative_results[1]))

**Content:**
1. [Alternative submodule:](#1)
    1. [Discrete modification](#2)
    1. [Percentage modification](#3)
    1. [Range modification](#4)
    1. [Alternative removal](#5)
    1. [General](#6)
1. [Criteria submodule:](#7)
    1. [Identification](#8)
    1. [Percentage modification](#9)
    1. [Range modification](#10)
    1. [Criteria removal](#11)
    1. [Weights scenarios](#12)
1. [Probabilistic submodule:](#13)
1. [Ranking submodule:](#8)
1. [Compromise submodule:](#8)
1. [Further use](#7)

<a id="1"></a><br/>
## 1. Alternative submodule 

**Note**: Alternative submodule includes functions for modification of values in decision matrix and alternative removal.

Let us consider following matrix, this matrix will be taken as an initial matrix for furhter function calls

In [4]:
matrix = np.array([
[4, 1, 6],
[2, 6, 3],
[9, 5, 7],
])
print('Initial matrix:')
display(Matrix(matrix))

Initial matrix:


Matrix([
[4, 1, 6],
[2, 6, 3],
[9, 5, 7]])

### 1.1. Discrete modification <a id="2"></a>

For each criterion we can define discrete values that will be set as a value. All possible combinations are generated.

In [24]:
discrete_values = np.array([[2, 3, 4], [1, 5, 6], [3, 4]], dtype='object')
pretty_print_alternative(alternative.discrete_modification(matrix, discrete_values))

Alternative index: 1
Criteria index: 1
Change: 1
Resulting decision matrix:


Matrix([
[4.0, 1.0, 6.0],
[2.0, 1.0, 3.0],
[9.0, 5.0, 7.0]])

The value of alternative 1 in the first criterion was changed for discrite value '2'

### 1.2. Percentage modification <a id="3"></a>

Percentage values can be set as an `int` to make it the same for all criteria, or by an array to specify value for specific criterion.

In [28]:
percentages = 5
# percentages = np.array([3, 2, 3])
pretty_print_alternative(alternative.percentage_modification(matrix, percentages)[0])

Alternative index: 0
Criteria index: 0
Change: -0.01
Resulting decision matrix:


Matrix([
[3.96, 1.0, 6.0],
[ 2.0, 6.0, 3.0],
[ 9.0, 5.0, 7.0]])

In the case of percentage modification the value of first alternative under first criterion changed by -0.01, which means -1%

### 1.3. Range modification <a id="4"></a>

Range values should be specified for each criterion (2d-array) or for each value in decision matrix (3d-array).

In [31]:
range_values = np.array([[6, 8], [2, 4], [4, 6.5]])
range_modification_results = alternative.range_modification(matrix, range_values)
pretty_print_alternative(range_modification_results[0])

Alternative index: 0
Criteria index: 0
Change: 6.0
Resulting decision matrix:


Matrix([
[6.0, 1.0, 6.0],
[2.0, 6.0, 3.0],
[9.0, 5.0, 7.0]])

The range modification modifies values in specified range, if step is not passed, it is set to 1. The value of first alternative, first criterion was set to 6. In the next step it will be set to 7.

In [57]:
display(Markdown('#### **Next step**'))
pretty_print_alternative(range_modification_results[1])

#### **Next step**

Alternative index: 0
Criteria index: 0
Change: 7.0
Resulting decision matrix:


Matrix([
[7.0, 1.0, 6.0],
[2.0, 6.0, 3.0],
[9.0, 5.0, 7.0]])

### 1.4. Alternative removal <a id="5"></a>

In [60]:
pretty_print_alternative_removal(alternative.remove_alternatives(matrix)[0])

Alternative index: 0
Resulting decision matrix:


Matrix([
[2, 6, 3],
[9, 5, 7]])

In [59]:
display(Markdown('#### **Next step**'))
pretty_print_alternative_removal(alternative.remove_alternatives(matrix)[1])

#### **Next step**

Alternative index: 1
Resulting decision matrix:


Matrix([
[4, 1, 6],
[9, 5, 7]])

### 1.5. General <a id="6"></a>

All functions provide additional parameters.

- Parameter `indexes` - provides a way to restrict the use of function to specific criteria. **In the case of alternative removal, this parameter specifies indexes of alternatives that should be removed**
- Parameter `direction` *(only percentage function)* - specifies direction of the modification for each column in the matrix. 
- Parameter `step` *(only range and percentage functions)* - specifies step of next change

**For example**:

In [14]:
direction = np.array([-1, 1, -1])
percentages = np.array([2, 4, 9])
indexes = np.array([[0, 2], 1], dtype='object')
step = np.array([2, 2, 3])
results = alternative.percentage_modification(matrix, percentages, direction, indexes, step)
display(Markdown('#### **This will provide change for all alternative at first for the first and third criterion from step to percentage value:**'))
pretty_print_alternative(results[0])
display(Markdown('#### **And separately for all alternatives for second criterion:**'))
pretty_print_alternative(results[3])

#### **This will provide change for all alternative at first for the first and third criterion from step to percentage value:**

Alternative index: 0
Criteria index: (0, 2)
Change: (-0.02, -0.03)
Resulting decision matrix:


Matrix([
[3.92, 1.0, 5.82],
[ 2.0, 6.0,  3.0],
[ 9.0, 5.0,  7.0]])

#### **And separately for all alternatives for second criterion:**

Alternative index: 0
Criteria index: 1
Change: 0.02
Resulting decision matrix:


Matrix([
[4.0, 1.02, 6.0],
[2.0,  6.0, 3.0],
[9.0,  5.0, 7.0]])

<a id="8"></a><br>
## 2. Criteria submodule

## 3. Probabilistic submodule

## 4. Ranking submodule

## 5. Compromise submodule

## 6. Further use <a id="100"></a>

For most of the functions that modifies the decision matrix or weights vector, the library includes a wrapper for calculating the preference values and raknings for the returned results.

In [3]:
import numpy as np
from pymcdm.methods import COMET, TOPSIS, VIKOR
from pymcdm.methods.comet_tools import MethodExpert

decision_matrix = np.array([[4, 1, 6], [2, 6, 3], [9, 5, 7]])
decision_problem_weights = np.ones(decision_matrix.shape[1])/decision_matrix.shape[1]
decision_problem_types = np.ones(decision_matrix.shape[1])

comet = COMET(np.vstack((np.min(decision_matrix, axis=0), np.max(decision_matrix, axis=0))).T, MethodExpert(TOPSIS(), decision_problem_weights, decision_problem_types))
topsis = TOPSIS()
vikor = VIKOR()

comet_pref = comet(decision_matrix)
topsis_pref = topsis(decision_matrix, decision_problem_weights, decision_problem_types)
vikor_pref = vikor(decision_matrix, decision_problem_weights, decision_problem_types)

## ICRA variables preparation
methods = {
        COMET: [['np.vstack((np.min(matrix, axis=0), np.max(matrix, axis=0))).T', 'MethodExpert(TOPSIS(), weights, types)'], ['matrix']],
        topsis: ['matrix', 'weights', 'types'],
        vikor: ['matrix', 'weights', 'types']
        }

ICRA_matrix = np.array([comet_pref, topsis_pref, vikor_pref]).T
method_types = np.array([1, 1, -1])

result = ICRA.iterative_compromise(methods, ICRA_matrix, method_types)
print(result.all_rankings)

[[[2. 3. 2.]
  [3. 2. 3.]
  [1. 1. 1.]]

 [[3. 3. 3.]
  [2. 2. 2.]
  [1. 1. 1.]]]
